### ISSUE TITLE
Add contract execute message documentation

### ISSUE THREAD

**Issue by meeragjoshi** [Y-Foundry-Dao/yfd-docs#16]
Some documentation is needed for forge, proposal, vault proposal, and vote executes, in addition to vote queries and new section for NFT executes and queries.

**Comment by rayraspberry** [comment]
@meeragjoshi please go to the dework site - and "claim" the bounty 
https://app.dework.xyz/y-foundry-dao/yfd-wiki?taskId=53d9ac07-28d0-4a47-bec1-ae12029ff608
